#!/bin/bash
set -e

USER_UID=${USER_UID:-$(id -u)}
USER_GID=${USER_GID:-$(id -g)}
APP_DIR=${APP_DIR:-$(pwd)}

echo Test0

docker build                       \
    --build-arg=USER_UID=$USER_UID \
    --build-arg=USER_GID=$USER_GID \
    -t app-build                   \
    .docker/docker-build

echo Test

docker build                       \
    --build-arg=USER_UID=$USER_UID \
    --build-arg=USER_GID=$USER_GID \
    -t app-build-cache             \
    .docker/docker-build-cache
docker create              \
    --name app-build-cache \
    app-build-cache || echo "Data container for build caches already exists, keep it for faster build executions."
docker run                         \
    --rm                           \
    --volumes-from app-build-cache \
    -v $APP_DIR:/workspace         \
    -w /workspace                  \
    app-build                      \
    /bin/bash -c "npm install && sbt test stage"
